#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely

do_sigint()
{
	echo "Y U no love me?!"
}

do_sigquit()
{
	rm /var/run/myscript.pid
	kill -9 $$
}

do_sigterm()
{
	echo "I hate the kill command"
	do_sigquit
}

trap do_sigterm SIGTERM
trap do_sigint SIGINT
trap do_sigquit SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
done